# Generated by Django 6.0.3 on 2026-05-20 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='お世話の名前')),
            ],
            options={
                'verbose_name': 'お世話の種類',
                'verbose_name_plural': 'お世話の種類',
            },
        ),
        migrations.CreateModel(
            name='Reptile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('species', models.CharField(max_length=100, verbose_name='種類')),
                ('morph', models.CharField(blank=True, max_length=100, verbose_name='モルフ')),
                ('sex', models.IntegerField(choices=[(0, '不明'), (1, '男の子'), (2, '女の子')], default=0, verbose_name='性別')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('adoption_date', models.DateField(blank=True, null=True, verbose_name='お迎え日')),
                ('record_end_date', models.DateField(blank=True, null=True, verbose_name='お別れ日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reptiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(verbose_name='記録日')),
                ('condition', models.IntegerField(choices=[(0, '良い'), (1, '普通'), (2, '悪い')], default=1, verbose_name='元気')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重(g)')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='体長(cm)')),
                ('feeding', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='給餌')),
                ('food_type_memo', models.CharField(blank=True, max_length=100, verbose_name='餌の種類')),
                ('feces', models.IntegerField(choices=[(0, '異常'), (1, '正常')], default=1, verbose_name='フン')),
                ('shedding', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0, verbose_name='脱皮')),
                ('image', models.ImageField(blank=True, null=True, upload_to='records/%y/%m/%d/', verbose_name='写真')),
                ('memo', models.CharField(blank=True, max_length=500, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_type', models.ManyToManyField(blank=True, related_name='records', to='reptile.caretype', verbose_name='本日のお世話内容')),
                ('reptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reptile.reptile')),
            ],
        ),
    ]
