# Generated by Django 6.0.3 on 2026-05-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='condition',
            field=models.IntegerField(choices=[('good', '元気'), ('normal', '普通'), ('bad', '元気がない')], default=1, verbose_name='元気'),
        ),
    ]
