# Generated by Django 6.0.3 on 2026-06-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='feces',
            field=models.IntegerField(blank=True, choices=[(0, '異常'), (1, '正常')], null=True, verbose_name='フン'),
        ),
        migrations.AlterField(
            model_name='record',
            name='feeding',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='給餌'),
        ),
        migrations.AlterField(
            model_name='record',
            name='shedding',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='脱皮'),
        ),
    ]
