# Generated by Django 6.0 on 2026-06-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptile',
            name='memo',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='メモ'),
        ),
    ]
