# Generated by Django 6.0.3 on 2026-05-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0002_alter_record_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='care_type',
            new_name='care_types',
        ),
        migrations.AlterField(
            model_name='record',
            name='condition',
            field=models.IntegerField(choices=[(0, '元気'), (1, '普通'), (2, '元気がない')], default=1, verbose_name='元気'),
        ),
    ]
