# Generated by Django 6.0.3 on 2026-06-28 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0004_reptileinvite_usershare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='food_type_memo',
            new_name='food_type',
        ),
        migrations.RenameField(
            model_name='reptile',
            old_name='owner',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='record',
            name='care_types',
        ),
        migrations.CreateModel(
            name='RecordCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_cares', to='reptile.caretype')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_cares', to='reptile.record')),
            ],
            options={
                'db_table': 'record_cares',
                'unique_together': {('record', 'care_type')},
            },
        ),
    ]
