# Generated by Django 6.0 on 2026-06-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='used',
            field=models.BooleanField(default=True),
        ),
    ]
