# Generated by Django 6.0.3 on 2026-05-20 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_schools_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name_plural': '学校'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ('age', '-score'), 'verbose_name_plural': '生徒'},
        ),
        migrations.AlterField(
            model_name='schools',
            name='name',
            field=models.CharField(max_length=20, verbose_name='学校名'),
        ),
        migrations.AlterField(
            model_name='students',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='user.schools'),
        ),
        migrations.AlterField(
            model_name='students',
            name='score',
            field=models.IntegerField(),
        ),
    ]
